### ISSUE TITLE
proceedings and collections contribution

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/rome2016#2]
Jahn, A., Il discorso di Claudio in Tac. Ann. XI 24 a confronto con la Tavola di Lione, in G. Reggi (ed.), Storici latini e storici greci di età imperiale, Atti del corso d’aggiornamento per docenti di latino e greco del Canton Ticino (Lugano, 17-19 ottobre 1990), Lugano 1993, 73-101.

becomes 

Jahn, A., Il discorso di Claudio in Tac. Ann. XI 24 a confronto con la Tavola di Lione, in G. Reggi (ed.), Storici latini e storici greci di età imperiale: Atti del corso d’aggiornamento per docenti di latino e greco del Canton Ticino, Lugano 17-18-19 ottobre 1990, 73–101, G. Casagrande, Lugano, 1993

can the page numbers be postponed?

**Comment by francescomambrini** [comment]
The formatting is right. In the bibliography style that we're using page numbers for chapters, inproceedings and incollections are placed before publisher and address
