### ISSUE TITLE
Long urls

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/rome2016#3]
long urls exceed pagewidth. e.g. committee, Modolo (38) n. 6

**Comment by francescomambrini** [comment]
The only solution is to use:
\usepackage[hyphenbreaks]{breakurl}
in the preamble

http://tex.stackexchange.com/questions/54946/how-to-break-long-url-in-an-item

**Comment by francescomambrini** [comment]
Or even better:
\usepackage{url}
\def\UrlBreaks{\do\/\do-}

https://norwied.wordpress.com/2012/07/10/how-to-break-long-urls-in-bibtex/

**Comment by francescomambrini** [comment]
It works!
